ifndef u
u:=sotatek
endif

deploy:
	rsync -avhzL --delete \
				--no-perms --no-owner --no-group \
				--exclude .git \
				--exclude .env \
				--exclude dist \
				--exclude node_modules \
				--exclude workers \
				--filter=":- .gitignore" \
				. $(u)@$(h):$(dir)/
	ssh $(u)@$(h) "cd $(dir); yarn"
	ssh $(u)@$(h) "cd $(dir); pm2 restart -user"

deploy-dev:
	make deploy h=172.16.1.22111 dir=/home/sotatek/votee-lending/

